app/app/Http/routes.php
<?php

Route::get('/', ['as' => 'index', function () {
    return view('welcome');
}]);

Route::resource('field-type', 'FieldTypeController', ['except' => [
    'create', 'show'
]]);

Route::resource('contact', 'ContactController');

Route::post('contact/{id}/detail', [
    'as' => 'contact.detail.store', 'uses' => 'ContactController@detailStore'
]);

Route::delete('contact/{idContact}/detail/{idDetail}', [
    'as' => 'contact.detail.destroy', 'uses' => 'ContactController@detailDestroy'
]);

app/app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table = 'contacts';
    public $timestamps = false;
    protected $fillable =  ['firstname', 'lastname'];

    public function details()
    {
        return $this->hasMany('App\ContactDetails');
    }
}

app/app/ContactDetails.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContactDetails extends Model
{
    protected $table = 'contact_details';
    public $timestamps = false;
    protected $fillable =  ['contact_id', 'field_type_id', 'value'];

    public function type()
    {
        return $this->hasOne('App\FieldType', 'id', 'field_type_id');
    }
}

app/app/FieldType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FieldType extends Model
{
    protected $table = 'field_types';
    public $timestamps = false;
    protected $fillable =  ['name', 'field_type', 'is_active'];
}

app/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\ContactDetails;
use App\FieldType;
use Illuminate\Http\Request;
use Validator;
use App\Contact;
use App\Http\Requests;
use Illuminate\Database\QueryException as QE;

class ContactController extends Controller
{
    public function index()
    {
        $contacts = Contact::all();
        return view('contact.index', ['contacts' => $contacts]);
    }

    public function create()
    {
        //
    }

    public function detailStore(Request $request, $id)
    {
        $contact = Contact::find($id);
        if (!$contact) {
            return redirect()->back()->withErrors('System error');
        }

        $validator = Validator::make($request->all(), [
            'contact_id' => 'required|exists:contacts,id',
            'field_type_id' => 'required|exists:field_types,id',
            'value' => 'max:255',
        ]);

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator);
        }

        $fieldType = FieldType::find($request->field_type_id);
        if (!$fieldType->is_active) {
            return redirect()->back()->withErrors('System error');
        }

        ContactDetails::create($request->all());

        return redirect(route('contact.show', $contact->id));
    }

    public function detailDestroy($idContact, $idDetail)
    {
        ContactDetails::destroy($idDetail);
        return redirect()->back();
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'firstname' => 'required|max:128',
            'lastname' => 'max:128',
        ]);

        if ($validator->fails()) {
            return redirect(route('contact.index'))
                ->withErrors($validator);
        }

        Contact::create($request->all());

        return redirect(route('contact.index'));
    }

    public function show($id)
    {
        $contact = Contact::find($id);
        $fieldTypes = FieldType::where('is_active', 1)->get();
        if (!$contact) {
            return redirect(route('contact.index'))->withErrors('System error');
        }
        return view('contact.show', ['contact' => $contact, 'fieldTypes' => $fieldTypes]);
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        try {
            Contact::destroy($id);
        } catch(QE $e) {
            $message = 'System error';
            return redirect(route('contact.index'))->withErrors($message);
        }
        return redirect(route('contact.index'));
    }
}

app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/app/Http/Controllers/FieldTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use App\FieldType;
use App\Http\Requests;
use Illuminate\Database\QueryException as QE;

class FieldTypeController extends Controller
{
    public function index()
    {
        $fieldTypes = FieldType::all();
        return view('field-type.index', ['fieldTypes' => $fieldTypes]);
    }

    public function create()
    {

    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:120',
            'field_type' => 'required|max:32',
        ]);

        if ($validator->fails()) {
            return redirect('/field-type')
                ->withErrors($validator);
        }

        $request->is_active
            ? $request->merge(array('is_active' => 1))
            : $request->merge(array('is_active' => 0));

        FieldType::create($request->all());

        return redirect(route('field-type.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $fieldType = FieldType::find($id);
        if (!$fieldType) {
            return redirect()->back()->withErrors('System error');
        }
        return view('field-type.edit', ['fieldType' => $fieldType]);
    }

    public function update(Request $request, $id)
    {
        $fieldType = FieldType::findOrFail($id);

        $request->is_active
            ? $request->merge(array('is_active' => 1))
            : $request->merge(array('is_active' => 0));

        $fieldType->update($request->all());

        if (!$fieldType) {
            return redirect()->back()->withErrors('System error');
        }

        return redirect(route('field-type.index'));
    }

    public function destroy($id)
    {
        try {
            FieldType::destroy($id);
        } catch(QE $e) {
            $message = 'System error';
            return redirect(route('field-type.index'))->withErrors($message);
        }

        return redirect(route('field-type.index'));
    }
}

app/resources/views/contact/edit.blade.php
@extends('layouts.master')

@section('title')
    Welcome!
@endsection

@section('content')
    <h2><a href="{{ route('field-type.index') }}">Field types</a> / Edit</h2>
    <form class="form-inline" role="form" method="POST" action="{{ route('field-type.update', $fieldType->id) }}">
        <div class="form-group">
            <label class="sr-only" for="name">Name:</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Name" value="{{ $fieldType->name }}" />
        </div>
        <div class="form-group">
            <label class="sr-only" for="type">Type:</label>
            <input type="text" name="field_type" class="form-control" id="type" placeholder="Type" value="{{ $fieldType->field_type }}" />
        </div>
        <div class="checkbox">
            <label><input type="checkbox" name="is_active" value="1" {{ $fieldType->is_active ? 'checked' : '' }} /> Active</label>
        </div>
        <input type="hidden" name="_token" value="{{ Session::token() }}" />
        <input type="hidden" name="_method" value="PUT" />
        <button type="submit" class="btn btn-default">Edit</button>
    </form>
    <br />
@endsection

app/resources/views/contact/index.blade.php
@extends('layouts.master')

@section('title')
    Welcome!
@endsection

@section('content')
    <h2>Contacts</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>User</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($contacts as $contact)
            <tr>
                <td>{{ $contact->firstname . ' ' . $contact->lastname }}</td>
                <td class="text-center col-md-2">
                    <div class="btn-group">
                        <a class="btn btn-default" href="{{ route('contact.show', $contact->id) }}">Show</a>
                    </div>
                    <div class="btn-group">
                        <form action="{{ route('contact.destroy', $contact->id) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger">
                                <i class="fa fa-trash"></i> Delete
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <form class="form-inline" role="form" method="POST" action="{{ route('contact.store') }}">
        <div class="form-group">
            <label class="sr-only" for="name">First name:</label>
            <input type="text" name="firstname" class="form-control" id="name" placeholder="First name" value="" />
        </div>
        <div class="form-group">
            <label class="sr-only" for="lastname">Type:</label>
            <input type="text" name="lastname" class="form-control" id="lastname" placeholder="Last name" value="" />
        </div>
        <input type="hidden" name="_token" value="{{ Session::token() }}" />
        <button type="submit" class="btn btn-default">Add new</button>
    </form>
    <br />
@endsection

app/resources/views/contact/show.blade.php
@extends('layouts.master')

@section('title')
    Welcome!
@endsection

@section('content')
    <h2><a href="{{ route('contact.index') }}">Contact</a> / Show {{ $contact->id }}</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>User</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $contact->firstname . ' ' . $contact->lastname }}</td>
                <td class="text-center col-md-3">
                    <div class="btn-group">
                        <a class="btn btn-default" href="{{ route('contact.edit', $contact->id) }}">Edit</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <h2>Details</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Type</th>
            <th>Value</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($contact->details as $detail)
            <tr>
                <td>{{ $detail->type->name }}</td>
                <td>{{ $detail->value }}</td>
                <td class="text-center col-md-3">
                    <div class="btn-group">
                        <a class="btn btn-default" href="{{ route('contact.edit', $contact->id) }}">Edit</a>
                    </div>
                    <div class="btn-group">
                        <form action="{{ route('contact.detail.destroy', ['idContact' => $contact->id, 'idDetail' => $detail->id]) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger">
                                <i class="fa fa-trash"></i> Delete
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <form class="form-inline" role="form" method="POST" action="{{ route('contact.detail.store', $contact->id) }}">
        <div class="form-group">
            <label for="sel1">Type:</label>
            <select class="form-control" id="sel1" name="field_type_id">
                @foreach($fieldTypes as $fieldType)
                    <option value="{{ $fieldType->id }}">{{ $fieldType->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label class="sr-only" for="value">Value:</label>
            <input type="text" name="value" class="form-control" id="value" placeholder="Value" value="" />
        </div>
        <input type="hidden" name="contact_id" value="{{ $contact->id }}" />
        <input type="hidden" name="_token" value="{{ Session::token() }}" />
        <button type="submit" class="btn btn-default">Add new</button>
    </form>
    <br />
@endsection

app/resources/views/field-type/edit.blade.php
@extends('layouts.master')

@section('title')
    Welcome!
@endsection

@section('content')
    <h2><a href="{{ route('field-type.index') }}">Field types</a> / Edit</h2>
    <form class="form-inline" role="form" method="POST" action="{{ route('field-type.update', $fieldType->id) }}">
        <div class="form-group">
            <label class="sr-only" for="name">Name:</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Name" value="{{ $fieldType->name }}" />
        </div>
        <div class="form-group">
            <label class="sr-only" for="type">Type:</label>
            <input type="text" name="field_type" class="form-control" id="type" placeholder="Type" value="{{ $fieldType->field_type }}" />
        </div>
        <div class="checkbox">
            <label><input type="checkbox" name="is_active" value="1" {{ $fieldType->is_active ? 'checked' : '' }} /> Active</label>
        </div>
        <input type="hidden" name="_token" value="{{ Session::token() }}" />
        <input type="hidden" name="_method" value="PUT" />
        <button type="submit" class="btn btn-default">Edit</button>
    </form>
    <br />
@endsection

app/resources/views/field-type/index.blade.php
@extends('layouts.master')

@section('title')
    Welcome!
@endsection

@section('content')
    <h2>Field types</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($fieldTypes as $fieldType)
            <tr>
                <td>{{ $fieldType->name }}</td>
                <td>{{ $fieldType->field_type }}</td>
                <td>{{ $fieldType->is_active ? 'Enabled' : 'Disabled' }}</td>
                <td class="text-center col-md-2">
                    <div class="btn-group">
                        <form action="{{ route('field-type.destroy', $fieldType->id) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger">
                                <i class="fa fa-trash"></i> Delete
                            </button>
                        </form>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-default" href="{{ route('field-type.edit', $fieldType->id) }}">Edit</a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <form class="form-inline" role="form" method="POST" action="{{ route('field-type.store') }}">
        <div class="form-group">
            <label class="sr-only" for="name">Name:</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Name" value="{{ old('name') }}" />
        </div>
        <div class="form-group">
            <label class="sr-only" for="type">Type:</label>
            <input type="text" name="field_type" class="form-control" id="type" placeholder="Type" value="{{ old('field_type') }}" />
        </div>
        <div class="checkbox">
            <label><input type="checkbox" name="is_active" value="1" /> Active</label>
        </div>
        <input type="hidden" name="_token" value="{{ Session::token() }}" />
        <button type="submit" class="btn btn-default">Add new</button>
    </form>
    <br />
@endsection

app/resources/views/includes/header.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ route('index') }}">Index</a>
            <a class="navbar-brand" href="{{ route('contact.index') }}">Contacts</a>
            <a class="navbar-brand" href="{{ route('field-type.index') }}">Field Types</a>
        </div>
    </div><!-- /.container-fluid -->
</nav>

@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{$error}}
        </div>
    @endforeach
@endif

app/resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>@yield('title')</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            @include('includes.header')
            @yield('content')
        </div>
    </body>
</html>